# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/demand.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/demand.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/demand.proto\x12\x06\x64\x65mand\"7\n\rDemandRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x19\n\x11quantity_consumed\x18\x02 \x01(\x05\"a\n\x0e\x44\x65mandResponse\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x18\n\x10\x63urrent_quantity\x18\x02 \x01(\x05\x12\x17\n\x0f\x62reach_detected\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2\x92\x01\n\rDemandService\x12=\n\x0cReportDemand\x12\x15.demand.DemandRequest\x1a\x16.demand.DemandResponse\x12\x42\n\rStreamDemands\x12\x15.demand.DemandRequest\x1a\x16.demand.DemandResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.demand_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEMANDREQUEST']._serialized_start=31
  _globals['_DEMANDREQUEST']._serialized_end=86
  _globals['_DEMANDRESPONSE']._serialized_start=88
  _globals['_DEMANDRESPONSE']._serialized_end=185
  _globals['_DEMANDSERVICE']._serialized_start=188
  _globals['_DEMANDSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
